---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # 여러분의 backend image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_c78de1d1a000
          env:
            - name: TZ
              value: Asia/Seoul
            - name: DATABASE_URL
              value: jdbc:mariadb://mariadb:3306/krampoline
          resources:
            requests:
              memory: 1Gi
          readinessProbe:
            httpGet:
              # 해당 /api 가 안  뚫려있으면 Ready 가 안되요.
              path: /api/test
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    # selector 가 app name 에 맞도록 주위해주세요.
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
